---
- name: Get the VPC ID
  ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ ec2_vpc_name }}-vpc"
    region: "{{ aws_region }}"
  register: vpc_net_info

- name: set variables
  set_fact:
    ec2_vpc_id: "{{vpc_net_info.vpcs[0].id}}"

- name: Get route information
  ec2_vpc_route_table_info:
    region: "{{ aws_region }}"
    filters:
      vpc_id: "{{ ec2_vpc_id }}"
  register: route_table_info

- name: Delete SG
  include_tasks: deletesg.yml

- name: Delete SG 
  include_tasks: deletesubnets.yml

- name: Delete SG
  include_tasks: deleteigw.yml

- name: Delete SG 
  include_tasks: deleteroutetable.yml

- name: Delete SG
  include_tasks: deletevpc.yml