---
- name: Create VPC
  ec2_vpc_net:
    name: "{{ ec2_vpc_name }}-vpc"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ aws_region }}"
    tags:
      Name: "{{ec2_vpc_name}}-vpc"
    state: present
  register: vpc_details

- name: Store VPC ID for future use
  set_fact:
    ec2_vpc_id: "{{vpc_details.vpc.id}}"

- debug: msg="Created VPC with ID {{ec2_vpc_id}}"