---
# lookup: id ensures that the main route table is updated instead of creating new RT.
# https://stackoverflow.com/a/45472581/682912
- name: Create route table rules to create a public subnet.
  ec2_vpc_route_table:
    vpc_id: '{{ec2_vpc_id}}'
    region: '{{ec2_region}}'
    subnets:
      - "{{subnet_id}}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: '{{ec2_vpc_igw_id}}'
  tags: route