---
- name: Create Main Security Group
  ec2_group:
    name: My Security Group
    description: My Security Group
    vpc_id: "{{ ec2_vpc_id }}"
    region: "{{ ec2_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
  register: security_group_details
- name: Store EC2 Group ID.
  set_fact:
   ec2_group_id : "{{security_group_details.group_id}}"