- name: Retrive EC2 instance info
  ec2_instance_info:
    filters:
      "tag:app": jenkins
      instance-state-name: ["running"]
  register: ec2_instances

- name: Launch an instance in target VPC
  ec2:
    key_name: "{{key_name}}"
    profile: "{{profile}}"
    region: "{{aws_region}}"
    instance_type: t2.micro
    image: "{{ image_id }}"
    wait: yes
    group_id: ["{{ ec2_vpc_sgs.security_groups[0].group_id }}"]
    count: "{{ number_of_instance }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet.subnets[0].subnet_id }}"
    instance_tags:
      app: jenkins
      name: Jenkins_instance
    assign_public_ip: yes
  register: ec2_details
  when: ec2_instances.instances|length < 1

- name: Add the newly created host so that we can further contact it
  add_host:
    name: "{{ec2_details.instances[0].public_ip}}"
    groups: webservers
  when: ec2_instances.instances|length < 1
- name: Wait for SSH to come up
  wait_for:
    host: "{{ec2_details.instances[0].public_ip}}"
    port: 22
    state: started
  when: ec2_instances.instances|length < 1

- name: Create DNS entry
  route53:
    state: present
    profile: "{{profile}}"
    zone: "{{domain_name}}"
    record: "jenkins.{{domain_name}}"
    type: CNAME
    ttl: 60
    value: "{{ec2_details.instances[0].public_ip}}"
  when: ec2_instances.instances|length < 1