---
- name: Retrive EC2 instance info
  ec2_instance_info:
    profile: "{{profile}}"
    filters:
      "tag:app": jenkins
      instance-state-name: ["running"]
  register: ec2_instances

- name: Get route53 details
  route53:
      profile: "{{profile}}"
      state: get
      zone: "{{domain_name}}"
      record: "jenkins.{{domain_name}}"
      type: CNAME
  register: rec

- name: Delete Route53
  route53:
    profile: "{{profile}}"
    state: absent
    zone: "{{domain_name}}"
    record: "{{ rec.set.record }}"
    ttl: "{{ rec.set.ttl }}"
    type: "{{ rec.set.type }}"
    value: "{{ rec.set.value }}"


- name: Terminate instance
  ec2:
    profile: "{{profile}}"
    state: absent
    instance_ids: '{{ ec2_instances.instances[0].instance_id}}'
    #instance_ids: '{{ ec2_instances }}'
    region: "{{aws_region}}"
    wait: yes



