---
- name: Install Open-JDK
  apt:
    name: "openjdk-8-jdk"
    state: "present"

- name: Ensure dependencies are installed.
  apt:
    name:
      - curl
      - apt-transport-https
      - gnupg
      - maven
      - docker.io
    state: present

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present

- name: add to sources.list
  command: "sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'"

- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes

- name: Ensure Jenkins is installed.
  apt:
    name: jenkins
    state: present
  register: jenkins_status

- name: Install NGINX
  apt:
    name: "nginx"
    state: present

- name: create letsencrypt directory
  file:
    name: /var/www/letsencrypt
    state: directory

- name: Remove default nginx config
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy nginx configuration in place.
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: Install certbot
  apt:
    name: "python-certbot-nginx"
    state: present

- name: Add user to group
  shell: "usermod -a -G docker jenkins" 

- name: Get certs
  shell: "certbot --nginx --noninteractive --agree-tos --email {{email_id}} -d jenkins.{{domain_name}}"

- name: Restart jenkins
  systemd:
    state: restarted
    name: jenkins

- name: Copy jenkins first admin password
  shell: "cat /var/lib/jenkins/secrets/initialAdminPassword"
  when: jenkins_status.changed == true
