---

- name: teardown_vpc
  hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - include_vars: vars/main.yml
  tasks:

    - name: Get the VPC ID
      ec2_vpc_net_info:
        filters:
          "tag:Name": "{{ ec2_vpc_name }}-vpc"
        region: "{{ aws_region }}"
      register: vpc_net_info

    - name: set variables
      set_fact:
        ec2_vpc_id: "{{vpc_net_info.vpcs[0].id}}"

    - name: Deleted EC2 security group for VPC
      ec2_group:
        name: "{{ ec2_vpc_name }}-sg"
        region: "{{ aws_region }}"
        vpc_id: "{{ ec2_vpc_id }}"
        state: absent
      register: delete_sg

    - name: Delete subnet
      ec2_vpc_subnet:
        region: "{{ aws_region }}"
        az: "{{ aws_region }}a"
        vpc_id: "{{ ec2_vpc_id }}"
        cidr: "{{ public_subnet_1_cidr }}"
        state: absent

    - name: Delete vpc internet gateway
      ec2_vpc_igw:
        region: "{{ aws_region }}"
        vpc_id: "{{ ec2_vpc_id }}"
        state: absent

    - name: Get route information
      ec2_vpc_route_table_info:
        region: "{{ aws_region }}"
        filters:
          vpc_id: "{{ ec2_vpc_id }}"
      register: route_table_info

    - name: Delete VPC public subnet route table
      ec2_vpc_route_table:
        region: "{{ aws_region }}"
        vpc_id: "{{ ec2_vpc_id }}"
        tags: 
          Name: "{{ec2_vpc_name}}-rt"
        state: absent

    - name: Delete VPC
      ec2_vpc_net:
        name: "{{ ec2_vpc_name }}-vpc"
        cidr_block: "{{ vpc_cidr_block }}"
        region: "{{ aws_region }}"
        state: absent